eduhub/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('account/',include('account.urls')),
    path('staff/',include('staff.urls')),
    path('student/',include('student.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('',index,name='home'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('courses/', courses, name='courses'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from account . models import *
# Create your models here.

class Course(models.Model):
    staff=models.ForeignKey(Staff,on_delete = models.CASCADE)
    course_image=models.ImageField(upload_to='Course_images/')
    title=models.CharField(max_length=200)
    description=models.TextField(max_length=250)
    

    def __str__(self):
        return self.title
    



    
class Contact(models.Model):
    name=models.CharField(max_length=200)
    phone=models.CharField(max_length=200)
    email=models.EmailField(max_length=200)
    message=models.TextField(max_length=250)

    def __str__(self):
        return self.name
    
    

templates/staff_templates/add_question.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>add-questions-page</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f2f2f2;
        }

        h1 {
            text-align: center;
            margin-top: 20px;
        }

        form {
            max-width: 600px;
            margin: 20px auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        fieldset {
            border: none;
            margin-bottom: 20px;
        }

        legend {
            font-weight: bold;
            margin-bottom: 10px;
        }

        label {
            display: block;
            margin-bottom: 5px;
        }

        input[type="text"],
        select {
            width: 100%;
            padding: 8px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
            margin-bottom: 10px;
        }

        button[type="submit"] {
            background-color: #016795;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 16px;
            margin-top: 10px;
        }

        button[type="submit"]:hover {
            background-color: slategray;
        }

        .error-message {
            color: red;
            margin-top: 5px;
        }
        
        /* Style for form fields rendered using {{ form.as_p }} */
        .form-field {
            margin-bottom: 10px;
        }

        .form-field label {
            font-weight: bold;
        }

        .form-field input[type="text"],
        .form-field select {
            width: calc(100% - 12px); /* Adjust the width to fit inside the form */
            padding: 8px;
        }
    </style>
</head>
<body>
    <h1>Add Questions</h1>
    <form method="post">
        {% csrf_token %}
        {{ question_form.as_p }}
        {{ choice_formset.management_form }}
        <fieldset>
            <legend>Choices</legend>
            {{ choice_formset.management_form }}
            {% for form in choice_formset %}
                <div class="form-field">
                    {{ form.text }}
                </div>
                <div class="form-field">
                    {{ form.is_correct.label_tag }}
                    {{ form.is_correct }}
                </div>
            {% endfor %}
        </fieldset>
        <button type="submit">Submit</button>
    </form>
</body>
</html>

templates/staff_templates/edit_staff_details.html
{% extends 'base.html' %} 
{% load static %} 
{% block title %}edit-staff-page{% endblock %} 
{% block content %}

<div class="container form">
    <h2>Edit Staff</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <input type="text"  name="username" value="{{user.username}}" placeholder="Enter your username">
        </div>
        <div class="form-group">
            <input type="text"  name="first_name" value="{{user.first_name}}" placeholder="Enter your firstname">
        </div>
        <div class="form-group">
            <input type="text"  name="last_name" value="{{user.last_name}}" placeholder="Enter your lastname">
        </div>
        <div class="form-group">
            <input type="email"  name="email" value="{{user.email}}" placeholder="Enter your email">
        </div>
        <div class="form-group">
            <input type="file"  name="profile_image" >
        </div>
        <input type="submit" value="Save" />
        <div class="link">
            <a href="{% url 'change_password' %}"> Change Password</a>
        </div>
    </form>
</div>

{% endblock %}

templates/staff_templates/manage_course.html
{% extends 'base.html' %}
{% block title %}manage-course-page{% endblock %}

{% block content %}
<div class="container manage-course" style="color: #fff; font-weight: bold;" >
    <div class="row">
        <div class="col-md-6">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_course_image">Course Image</label>
                    {{ form.course_image }}
                </div>
                <div class="form-group">
                    <label for="id_title">Title</label>
                    {{ form.title }}
                </div>
                <div class="form-group">
                    <label for="id_description">Description</label>
                    {{ form.description }}
                </div>
                <input type="submit" value="Add"></input>
            </form>
        </div>
        <div class="col-md-6 mt-4">
            <ul class="list-group">
                {% for course in courses %}
                <li class="list-group-item">
                    <div class="d-flex justify-content-between align-items-center">
                        <span>{{ course.title }}</span>
                        <form method="POST" action="{% url 'delete_course' course.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger"><i class="fa-solid fa-trash"></i></button>
                            <a href="{% url 'update_course' course.id %}" class="btn btn-warning"><i class="fas fa-edit"></i></a>
                        </form>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

templates/staff_templates/notifications.html
{% extends 'base.html' %}
{% block title %}create-notification-page{% endblock %}

{% block content %}
<div class="container mt-5">
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <textarea class="form-control" name="message" rows="8" placeholder="Enter your notification"></textarea>
        </div>
        {% if messages %}
        <div class="alert alert-success" role="alert">
            {% for message in messages %}
            {{ message }}
            {% endfor %}
        </div>
        {% endif %}
        <button type="submit" class="btn btn-custom-3">Send Notification</button>
    </form>
</div>
{% endblock %}

templates/staff_templates/question_list.html
{% extends 'base.html' %} 
{% load static %} 
{% block title %}questions-page{% endblock %} 
{% block content %}
    <div class="container mt-5">
        <table class="table">
            <thead>
                <tr>
                    <th>Question</th>
                    <th>Choices</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for question in questions %}
                    <tr>
                        <td>{{ question.text }}</td>
                        <td>
                            {% for choice in choices %}
                                {% if choice.question == question %}
                                    {{ choice.text }} <br>
                                {% endif %}
                            {% endfor %}
                        </td>
                        <td>
                            <a href="{% url 'delete_question' question.id %}">
                                <button class="btn btn-danger"><i class="fa-solid fa-trash"></i></button>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="add-link">
            <a href="{% url 'add_question' %}">Add Question</a>
        </div>
    </div>
{% endblock %}

templates/staff_templates/staff_dashboard.html
{% extends 'base.html' %} 
{% load static %} 
{% block title %}staff-dashboard-page{% endblock %} 
{% block content %}
<body style="background-color: bisque;">
    
<h4 style="color: #fff;"><marquee behavior="alternate" direction="right" scrollamount="12" style="background-color: dimgray">.........WELCOME TO {{user.username}} PAGE.........</marquee></h4>

        <div class="container">
            <div class="row">
                <div class="col-md-6 mb-4">
                    <div class="card text-white bg-secondary mt-5 ml-2" style="max-width: 18rem;">
                        <div class="card-header"><h3>{{user.username}}</h3></div>
                        <div class="card-body">
                          <h1 class="card-title">ID : {{ user.id }}</h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>

            <div class="container">
                <div class="row">
                    <div class="col-md-6 mb-4">
                        <div class="card text-white bg-secondary mt-5 ml-2" style="max-width: 18rem;">
                            <div class="card-header"><h3>Total Students</h3></div>
                            <div class="card-body">
                              <h1 class="card-title">{{ total_students }}</h1>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

</body>
               
    






{% endblock %}



{% if profile_image %}
<img src="{{ profile_image }}" alt="Profile Image">
{% else %}
<p>No profile image available.</p>
{% endif %}

templates/staff_templates/staff_feedback.html
{% extends 'base.html' %} 
{% load static %} 
{% block title %}staff-feedback-page{% endblock %} 
{% block content %}

<h1>Feedback Received</h1>
    <ul>
        {% for feedback in feedbacks %}
        <li>{{ feedback.message }}</li>
        {% endfor %}
    </ul>


{% endblock %}

templates/staff_templates/staff_signup.html
{% extends 'base.html' %} 
{% load static %} 
{% block title %}staff-signup-page{% endblock %} 
{% block content %}

<div class="container form">
    <h2>Staff Signup</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <input type="text"  name="username" placeholder="Enter your username">
        </div>
        <div class="form-group">
            <input type="text"  name="first_name" placeholder="Enter your firstname">
        </div>
        <div class="form-group">
            <input type="text"  name="last_name" placeholder="Enter your lastname">
        </div>
        <div class="form-group">
            <input type="email"  name="email" placeholder="Enter your email">
        </div>
        <div class="form-group">
            <input type="file"  name="profile_image">
        </div>
        <div class="form-group">
            <input type="password" name="password1" placeholder="Enter your password">
        </div>
        <div class="form-group">
            <input type="password" name="password2" placeholder="Confirm your password">
        </div>
        <input type="submit" value="Signup" />
        <div class="link">
            <p>Already have an account? <a href="{% url 'login' %}"> Login</a></p>
        </div>
    </form>
</div>

{% endblock %}

templates/staff_templates/update_course.html
{% extends 'base.html' %}
{% block title %}update-course-page{% endblock %}

{% block content %}
<div class="container manage-course">
    <div class="row">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label>Course Image</label>
                    {{ form.course_image }}
                </div>
                <div class="form-group">
                    <label>Title</label>
                    {{ form.title }}
                </div>
                <div class="form-group">
                    <label>Description</label>
                    {{ form.description }}
                </div>
                <input type="submit" value="Update"></input>
            </form>
    </div>
</div>
{% endblock %}

templates/staff_templates/upload_study_material.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Upload Study Material</title>
</head>
<body>
    <h2>Upload Study Material</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upload</button>
    </form>
</body>
</html>